### PR TITLE
Cc pre 8 maint merge

### PR DESCRIPTION
**Pull request by Tom-Rees**
Merge of changes that needed forward applying to V8

### CODE REVIEW

**Comment by Tom-Rees** [comment]
Hi Steve,

I just wanted to check that doing a merge like this won't break the sfr-diffs tool when we come to making our first maint release.

This merge commit won't have the sfr branch itself, but one of the commits (385b778) contains the name so hopefully it will be picked up?

Thanks,
Tom

**Comment by steelyvoid** [comment]
Good point.  Yes, hopefully it will. 

Can you do the merge and then check whether it does should up on an 8.0.0-1-1.0.0 -> CC_8_maint sfr diff?  If it doesn't, we might need to do a bit of tedious bookkeeping to remind ourselves of SFRs missed

**Comment by Tom-Rees** [comment]
Yup, all looking good :)

**Comment by steelyvoid** [comment]
Good.  I think we can assume that any CC_X_pre_maint branch fixes will have “Merge from SFR….” logs in them from the original fix, which will propagate into the CC_X_maint branch.

**Pull request merged**
